server {
  listen 80;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /graphql {
    proxy_pass http://3.22.171.236:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location /api/operaciones/ {
    rewrite ^/api/operaciones/(.*) /$1 break;
    proxy_pass http://34.10.181.185:8001;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /api/ia/ {
    rewrite ^/api/ia/(.*) /$1 break;
    proxy_pass http://34.30.80.191:8002;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }
}
